name: Update Berita Otomatis

on:
  schedule:
    # ===================================================================
    # PENGATURAN WAKTU SCRAP ULANG ADA DI SINI
    # '0 */6 * * *' artinya berjalan setiap 6 jam.
    # Ubah menjadi '0 * * * *' untuk berjalan setiap jam.
    # Ubah menjadi '0 0 * * *' untuk berjalan sekali sehari pada tengah malam UTC.
    # ===================================================================
    - cron: '0 */6 * * *'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script to generate site
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python run.py

      - name: Commit and push if there are changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "Berita Otomatis: Update konten pada $(date -u)"
            git push
          else
            echo "Tidak ada perubahan konten, commit dilewati."
          fi
